import { siteUrl } from "./urls";
export const image = (name) => siteUrl(`assets/img/${name}.webp`);
export const photos = [
  {
    id: "summer",
    src: image("chalupa-summer-panorama-lossless"),
    title: "Chalupa v létě",
    category: "Exteriér",
    alt: "Chalupa u Bedýnků se zahradou v létě",
    width: 1915,
    height: 821,
  },
  {
    id: "winter",
    src: image("chalupa-winter-panorama-lossless"),
    title: "Chalupa v zimě",
    category: "Exteriér",
    alt: "Chalupa u Bedýnků pod sněhem",
    width: 1918,
    height: 820,
  },
  {
    id: "living",
    src: image("obyvaci-pokoj-editorial"),
    title: "Obývací pokoj",
    category: "Interiér",
    alt: "Obývací pokoj s kamenným krbem a pohovkou",
    width: 1672,
    height: 941,
  },
  {
    id: "pergola",
    src: image("pergola-editorial"),
    title: "Pergola s grilem",
    category: "Exteriér",
    alt: "Krytá dřevěná pergola se stolem a grilem",
    width: 1536,
    height: 1024,
  },
  {
    id: "room1",
    src: image("loznice-1-editorial"),
    title: "Ložnice 01",
    category: "Pokoje",
    alt: "První podkrovní ložnice s dvoulůžkem a palandou",
    width: 1536,
    height: 1024,
  },
  {
    id: "room2",
    src: image("loznice-2-editorial"),
    title: "Ložnice 02",
    category: "Pokoje",
    alt: "Druhá ložnice s dvoulůžkem a samostatnými postelemi",
    width: 1536,
    height: 1024,
  },
  {
    id: "room3",
    src: image("loznice-3-editorial"),
    title: "Ložnice 03",
    category: "Pokoje",
    alt: "Třetí podkrovní ložnice",
    width: 1536,
    height: 1024,
  },
  {
    id: "kitchen",
    src: image("kuchyn-editorial"),
    title: "Kuchyň",
    category: "Interiér",
    alt: "Plně vybavená kuchyň chalupy",
    width: 1536,
    height: 1024,
  },
  {
    id: "sauna",
    src: image("sauna-horizontal"),
    title: "Finská sauna",
    category: "Interiér",
    alt: "Finská sauna v chalupě",
    width: 1659,
    height: 948,
  },
  {
    id: "playground",
    src: image("pohadkova-vesnicka-editorial"),
    title: "Pohádková vesnička",
    category: "Okolí",
    alt: "Pohádková hrací vesnička vedle chalupy",
    width: 1085,
    height: 1450,
  },
  {
    id: "ski",
    src: image("sjezdovka-editorial"),
    title: "Sjezdovky v okolí",
    category: "Okolí",
    alt: "Sjezdovka v Prkenném Dole",
    width: 1536,
    height: 1024,
  },
];
export const photoById = (id) => photos.find((photo) => photo.id === id);
export const navigation = [
  ["index", "Chalupa"],
  ["ubytovani", "Ubytování"],
  ["aktivity", "Okolí"],
  ["cenik", "Ceník"],
  ["kontakt", "Kontakt"],
];
export const pageTitles = {
  index: "Chalupa u Bedýnků",
  ubytovani: "Ubytování",
  aktivity: "Aktivity a výlety",
  cenik: "Ceník",
  kontakt: "Kontakt",
  rezervace: "Poptávka pobytu",
  pokyny: "Informace před příjezdem",
  "provozni-rad": "Provozní řád",
};
export const prices = [
  {
    id: "off",
    label: "Mimo sezonu",
    detail: "Duben, květen, září–prosinec mimo svátky",
    week: 20000,
    weekend: 14000,
  },
  {
    id: "summer",
    label: "Letní sezona",
    detail: "Červen, červenec, srpen",
    week: 34000,
    weekend: 16000,
  },
  {
    id: "winter",
    label: "Zimní sezona",
    detail: "Leden, únor, březen",
    week: 34000,
    weekend: 16000,
  },
  {
    id: "spring",
    label: "Jarní prázdniny",
    detail: "Podle termínu prázdnin",
    week: 33000,
    weekend: null,
  },
  {
    id: "easter",
    label: "Velikonoce",
    detail: "Velikonoční pobyty",
    week: 22000,
    weekend: 18000,
  },
  {
    id: "christmas",
    label: "Vánoce",
    detail: "Vánoční pobyty",
    week: 24000,
    weekend: null,
  },
  {
    id: "newyear",
    label: "Silvestr",
    detail: "Silvestrovský týden",
    week: 50000,
    weekend: null,
  },
];
export const money = (value) =>
  new Intl.NumberFormat("cs-CZ").format(value) + " Kč";
export const faqs = [
  [
    "Je chalupa jen pro naši skupinu?",
    "Ano. Pronajímáme celý objekt pro 2 až 14 osob. K dispozici máte všechny pokoje, kuchyň, společenskou místnost i pergolu.",
  ],
  [
    "Jaká je minimální délka pobytu?",
    "Minimálně 2 noci. Týdenní pobyty jsou od soboty do soboty. Víkendy mimo sezonu domlouváme podle termínu a počtu osob.",
  ],
  [
    "Můžeme přijet se psem?",
    "Menší vychovaný pes je možný po předchozí domluvě. Uveďte ho prosím do poptávky.",
  ],
  [
    "Jak se platí pobyt?",
    "Záloha je 50 % ceny, zbytek se doplácí měsíc před příjezdem. Při příjezdu se skládá vratná kauce 5 000 Kč.",
  ],
  [
    "Kdy je příjezd a odjezd?",
    "Příjezd od 16:00, odjezd do 10:00. Správcovou kontaktujte přibližně hodinu před příjezdem.",
  ],
];
export const activities = [
  {
    title: "Lyžování",
    category: "Zima",
    distance: "300 m",
    text: "Ski areál Arakis přibližně 300 m od chalupy. Areál Bret je hned vedle.",
    icon: "snow",
  },
  {
    title: "Běžky",
    category: "Zima",
    distance: "Krkonoše",
    text: "Trasy směrem k Rýchorské boudě a napojení na krkonošskou magistrálu.",
    icon: "mountain",
  },
  {
    title: "Rýchorský prales",
    category: "Léto",
    distance: "2 km",
    text: "Pěší výlety po Rýchorách a do krkonošských lesů.",
    icon: "tree",
  },
  {
    title: "Stachelberg a Eliška",
    category: "Léto",
    distance: "3 km",
    text: "Pohraniční pevnost a rozhledna. Cíle pro kratší výlet.",
    icon: "mountain",
  },
  {
    title: "Cyklotrasy Žacléřskem",
    category: "Léto",
    distance: "Žacléřsko",
    text: "Trasy po okolí. Kola uložíte do uzamykatelné úschovny u chalupy.",
    icon: "bike",
  },
  {
    title: "Pohádková vesnička",
    category: "S dětmi",
    distance: "Vedle chalupy",
    text: "Pohádkové domečky, houpačky, klouzačky a trampolína.",
    icon: "tree",
  },
  {
    title: "Aquapark Trutnov",
    category: "S dětmi",
    distance: "10 km",
    text: "Možnost programu při horším počasí.",
    icon: "water",
  },
  {
    title: "Janské Lázně a Černá Hora",
    category: "Léto",
    distance: "16 km",
    text: "Další výlety v Krkonoších dostupné autem.",
    icon: "mountain",
  },
];
